// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using UniMap360.Models;

#nullable disable

namespace UniMap360.Migrations
{
    [DbContext(typeof(UniMap360ProContext))]
    [Migration("20260510101024_AddAvatarUrl")]
    partial class AddAvatarUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniMap360.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedReason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA58670C35F96");

                    b.HasIndex(new[] { "Email" }, "UQ__Accounts__A9D1053467B8D8AF")
                        .IsUnique();

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("UniMap360.Models.AdminAuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AuditID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AdminAccountId")
                        .HasColumnType("int")
                        .HasColumnName("AdminAccountID");

                    b.Property<string>("AfterJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AuditId")
                        .HasName("PK_AdminAuditLogs");

                    b.HasIndex(new[] { "AdminAccountId", "CreatedAt" }, "IX_AdminAuditLogs_Admin_Time");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_AdminAuditLogs_Target");

                    b.ToTable("AdminAuditLogs", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key")
                        .HasName("PK_AppSettings");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoryType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2BACFFCD62");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("UniMap360.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("direct");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConversationId")
                        .HasName("PK_Conversations");

                    b.HasIndex(new[] { "LastMessageAt" }, "IX_Conversations_LastMessageAt");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastReadMessageID");

                    b.HasKey("ConversationId", "AccountId")
                        .HasName("PK_ConversationParticipants");

                    b.HasIndex(new[] { "AccountId", "IsArchived", "ConversationId" }, "IX_ConversationParticipants_Account_Archived_Conversation");

                    b.HasIndex(new[] { "ConversationId" }, "IX_ConversationParticipants_Conversation");

                    b.ToTable("ConversationParticipants", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("EmployerId")
                        .HasName("PK__Employer__CA445241FBAC3731");

                    b.HasIndex(new[] { "TaxCode" }, "UQ__Employer__12945A28C67BD57F")
                        .IsUnique()
                        .HasFilter("[TaxCode] IS NOT NULL");

                    b.HasIndex(new[] { "AccountId" }, "UQ__Employer__349DA587D082AB93")
                        .IsUnique();

                    b.ToTable("EmployerProfiles");
                });

            modelBuilder.Entity("UniMap360.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FavoriteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__CE74FAF5B7788E00");

                    b.HasIndex("StudentId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Idcard")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("IDCard");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("HostId")
                        .HasName("PK__HostProf__08D4870CF2133F30");

                    b.HasIndex(new[] { "AccountId" }, "UQ__HostProf__349DA58749AA4188")
                        .IsUnique();

                    b.HasIndex(new[] { "Idcard" }, "UQ__HostProf__43A2A4E30AC952B8")
                        .IsUnique()
                        .HasFilter("[IDCard] IS NOT NULL");

                    b.ToTable("HostProfiles");
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int")
                        .HasColumnName("EmployerID");

                    b.Property<bool?>("IsExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SourceURL");

                    b.HasKey("JobId")
                        .HasName("PK__Jobs__056690E21424BEAF");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("UniMap360.Models.JobApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CvPublicId")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("CvPublicID");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("CvURL");

                    b.Property<int>("JobId")
                        .HasColumnType("int")
                        .HasColumnName("JobID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("ApplicationId")
                        .HasName("PK__JobAppli__C93A4F791661E97C");

                    b.HasIndex("JobId");

                    b.HasIndex("StudentId");

                    b.ToTable("JobApplications", null, t =>
                        {
                            t.HasTrigger("tr_HoSoUngTuyen_LogTrangThai");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UniMap360.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Geometry>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullAddressNormalized")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WardName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA477A66ECEEE");

                    b.HasIndex(new[] { "Coordinates" }, "IX_Location_Coordinates");

                    b.HasIndex(new[] { "ProvinceName" }, "IX_Location_ProvinceName");

                    b.HasIndex(new[] { "ProvinceName", "DistrictName" }, "IX_Location_Province_District");

                    b.HasIndex(new[] { "ProvinceName", "DistrictName", "WardName" }, "IX_Location_Province_District_Ward");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("UniMap360.Models.Medium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MediaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<bool?>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MediaURL");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MediaId")
                        .HasName("PK__Media__B2C2B5AF03484D12");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("UniMap360.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("ConversationID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("int")
                        .HasColumnName("SenderAccountID");

                    b.HasKey("MessageId")
                        .HasName("PK_Messages");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "IX_Messages_Conversation_Created");

                    b.HasIndex(new[] { "ConversationId", "MessageId" }, "IX_Messages_Conversation_Message");

                    b.HasIndex(new[] { "SenderAccountId", "CreatedAt" }, "IX_Messages_Sender_Created");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NotificationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MetaJSON");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipientAccountId")
                        .HasColumnType("int")
                        .HasColumnName("RecipientAccountID");

                    b.Property<int?>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("NotificationId")
                        .HasName("PK_Notifications");

                    b.HasIndex(new[] { "RecipientAccountId", "IsRead", "CreatedAt" }, "IX_Notifications_Recipient_Read_Time");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_Notifications_Target");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<int>("TargetId")
                        .HasColumnType("int")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AEF54E702E");

                    b.HasIndex(new[] { "StudentId", "TargetType", "TargetId" }, "UX_Review_Student_Target")
                        .IsUnique()
                        .HasFilter("[TargetType] IS NOT NULL");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("UniMap360.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("HostID");

                    b.Property<bool?>("IsExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoomStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SourceURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__32863919894EE30F");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HostId");

                    b.HasIndex("LocationId");

                    b.ToTable("Rooms", t =>
                        {
                            t.HasTrigger("trg_LogPriceChange");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UniMap360.Models.RoomViewingAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AppointmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("HostId")
                        .HasColumnType("int")
                        .HasColumnName("HostID");

                    b.Property<string>("HostResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<string>("StudentNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("SuggestedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("AppointmentId")
                        .HasName("PK_RoomViewingAppointments");

                    b.HasIndex(new[] { "HostId", "Status", "ScheduledAt" }, "IX_RoomViewingAppointments_Host_Status_Scheduled");

                    b.HasIndex(new[] { "RoomId", "ScheduledAt" }, "IX_RoomViewingAppointments_Room_Scheduled");

                    b.HasIndex(new[] { "StudentId", "Status", "CreatedAt" }, "IX_RoomViewingAppointments_Student_Status_Created");

                    b.ToTable("RoomViewingAppointments", null, t =>
                        {
                            t.HasTrigger("tr_LichXemPhong_LogTrangThai");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Cvlink")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CVLink");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("University")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("StudentId")
                        .HasName("PK__StudentP__32C52A79F5EEC15A");

                    b.HasIndex(new[] { "AccountId" }, "UQ__StudentP__349DA5873B5BC4FE")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("UniMap360.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LogAction")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LogId")
                        .HasName("PK__SystemLo__5E5499A8D6B10865");

                    b.HasIndex("AccountId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("UniMap360.Models.VGlobalMapFeed", b =>
                {
                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    b.Property<bool?>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SourceURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.ToTable((string)null);

                    b.ToView("v_GlobalMapFeed", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.ConversationParticipant", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationParticipants_Accounts");

                    b.HasOne("UniMap360.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationParticipants_Conversations");

                    b.Navigation("Account");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("UniMap360.Models.EmployerProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Emp_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Favorite", b =>
                {
                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("Favorites")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("HostProfile")
                        .HasForeignKey("UniMap360.Models.HostProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Host_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.HasOne("UniMap360.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Cat");

                    b.HasOne("UniMap360.Models.EmployerProfile", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Emp");

                    b.HasOne("UniMap360.Models.Location", "Location")
                        .WithMany("Jobs")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Loc");

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniMap360.Models.JobApplication", b =>
                {
                    b.HasOne("UniMap360.Models.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_App_Job");

                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("JobApplications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_App_Student");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.Message", b =>
                {
                    b.HasOne("UniMap360.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Conversations");

                    b.HasOne("UniMap360.Models.Account", "SenderAccount")
                        .WithMany("Messages")
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Accounts");

                    b.Navigation("Conversation");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("UniMap360.Models.Notification", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "RecipientAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Accounts");

                    b.Navigation("RecipientAccount");
                });

            modelBuilder.Entity("UniMap360.Models.Review", b =>
                {
                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Review_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.Room", b =>
                {
                    b.HasOne("UniMap360.Models.Category", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Cat");

                    b.HasOne("UniMap360.Models.HostProfile", "Host")
                        .WithMany("Rooms")
                        .HasForeignKey("HostId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Host");

                    b.HasOne("UniMap360.Models.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Loc");

                    b.Navigation("Category");

                    b.Navigation("Host");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniMap360.Models.RoomViewingAppointment", b =>
                {
                    b.HasOne("UniMap360.Models.HostProfile", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Host");

                    b.HasOne("UniMap360.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Room");

                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Student");

                    b.Navigation("Host");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("StudentProfile")
                        .HasForeignKey("UniMap360.Models.StudentProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Student_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.SystemLog", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany("SystemLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Log_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Account", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("EmployerProfile");

                    b.Navigation("HostProfile");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("StudentProfile");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("UniMap360.Models.Category", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("UniMap360.Models.Location", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("JobApplications");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
