// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniMap360.Models;

#nullable disable

namespace UniMap360.Migrations.PostgreSql
{
    [DbContext(typeof(UniMap360PostgresContext))]
    [Migration("20260606111711_AddSourceUrlUniqueIndexes")]
    partial class AddSourceUrlUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniMap360.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LockedReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserRole")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA58670C35F96");

                    b.HasIndex(new[] { "Email" }, "UQ__Accounts__A9D1053467B8D8AF")
                        .IsUnique();

                    b.ToTable("TaiKhoan", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.AccountSubscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubscriptionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("PlanId");

                    b.ToTable("AccountSubscriptions");
                });

            modelBuilder.Entity("UniMap360.Models.AdminAuditLog", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AuditID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AdminAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AdminAccountID");

                    b.Property<string>("AfterJson")
                        .HasColumnType("text");

                    b.Property<string>("BeforeJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("AuditId")
                        .HasName("PK_AdminAuditLogs");

                    b.HasIndex(new[] { "AdminAccountId", "CreatedAt" }, "IX_AdminAuditLogs_Admin_Time");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_AdminAuditLogs_Target");

                    b.ToTable("NhatKyKiemToanQuanTri", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key")
                        .HasName("PK_AppSettings");

                    b.ToTable("CaiDatUngDung", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CategoryType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2BACFFCD62");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.ContentReport", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReportID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReportId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("OwnerAccountIdSnapshot")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ReporterAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("ReporterAccountID");

                    b.Property<string>("ResolutionAction")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByAdminAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("ReviewedByAdminAccountID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetTitleSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("ReportId");

                    b.HasIndex("ReviewedByAdminAccountId");

                    b.HasIndex(new[] { "ReporterAccountId", "CreatedAt" }, "IX_ContentReports_ReporterAccountId_CreatedAt");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_ContentReports_Status_CreatedAt");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_ContentReports_TargetType_TargetId");

                    b.HasIndex(new[] { "TargetType", "TargetId", "Status" }, "IX_ContentReports_TargetType_TargetId_Status");

                    b.HasIndex(new[] { "ReporterAccountId", "TargetType", "TargetId" }, "UQ_ContentReports_Reporter_Target_Active")
                        .IsUnique()
                        .HasFilter("\"Status\" IN ('Pending', 'Reviewing')");

                    b.ToTable("ContentReports", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ConversationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("direct");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ConversationId")
                        .HasName("PK_Conversations");

                    b.HasIndex(new[] { "LastMessageAt" }, "IX_Conversations_LastMessageAt");

                    b.ToTable("CuocTroChuyen", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.ConversationParticipant", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("ConversationID");

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("LastReadMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("LastReadMessageID");

                    b.HasKey("ConversationId", "AccountId")
                        .HasName("PK_ConversationParticipants");

                    b.HasIndex(new[] { "AccountId", "IsArchived", "ConversationId" }, "IX_ConversationParticipants_Account_Archived_Conversation");

                    b.HasIndex(new[] { "ConversationId" }, "IX_ConversationParticipants_Conversation");

                    b.ToTable("ThanhVienCuocTroChuyen", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.Property<int>("EmployerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("EmployerID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployerId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("EmployerId")
                        .HasName("PK__Employer__CA445241FBAC3731");

                    b.HasIndex(new[] { "TaxCode" }, "UQ__Employer__12945A28C67BD57F")
                        .IsUnique();

                    b.HasIndex(new[] { "AccountId" }, "UQ__Employer__349DA587D082AB93")
                        .IsUnique();

                    b.ToTable("HoSoNhaTuyenDung", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("FavoriteID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavoriteId"));

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__CE74FAF5B7788E00");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_YeuThich_Target");

                    b.HasIndex(new[] { "StudentId", "TargetType", "TargetId" }, "UX_YeuThich_Student_Target")
                        .IsUnique();

                    b.ToTable("YeuThich", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.FeaturedListing", b =>
                {
                    b.Property<int>("FeaturedListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeaturedListingId"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeaturedListingId");

                    b.HasIndex("Status", "EndsAt")
                        .HasDatabaseName("IX_FeaturedListings_Status_EndsAt");

                    b.HasIndex("OwnerAccountId", "FeatureType", "Status")
                        .HasDatabaseName("IX_FeaturedListings_Owner_Type_Status");

                    b.HasIndex("TargetType", "TargetId", "FeatureType", "Status")
                        .HasDatabaseName("IX_FeaturedListings_Target_Type_Status");

                    b.ToTable("FeaturedListings");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.Property<int>("HostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HostID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Idcard")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("IDCard");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("character varying(15)");

                    b.HasKey("HostId")
                        .HasName("PK__HostProf__08D4870CF2133F30");

                    b.HasIndex(new[] { "AccountId" }, "UQ__HostProf__349DA58749AA4188")
                        .IsUnique();

                    b.HasIndex(new[] { "Idcard" }, "UQ__HostProf__43A2A4E30AC952B8")
                        .IsUnique();

                    b.ToTable("HoSoChuTro", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("JobID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EmployerId")
                        .HasColumnType("integer")
                        .HasColumnName("EmployerID");

                    b.Property<bool?>("IsExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("JobStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("JobType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("LocationID");

                    b.Property<string>("SalaryRange")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("SourceURL");

                    b.HasKey("JobId")
                        .HasName("PK__Jobs__056690E21424BEAF");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployerId");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "SourceUrl" }, "UX_ViecLam_SourceURL")
                        .IsUnique();

                    b.ToTable("ViecLam", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.JobApplication", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ApplicationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ApplicationId"));

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CvPublicId")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("CvPublicID");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("CvURL");

                    b.Property<int>("JobId")
                        .HasColumnType("integer")
                        .HasColumnName("JobID");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.HasKey("ApplicationId")
                        .HasName("PK__JobAppli__C93A4F791661E97C");

                    b.HasIndex("JobId");

                    b.HasIndex("StudentId");

                    b.ToTable("HoSoUngTuyen", null, t =>
                        {
                            t.HasTrigger("tr_HoSoUngTuyen_LogTrangThai");
                        });
                });

            modelBuilder.Entity("UniMap360.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LocationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LocationId"));

                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("Coordinates")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DistrictCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DistrictName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FullAddressNormalized")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GeocodeSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("GeocodedLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("GeocodedLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("HouseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LocationConfidence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("LocationDistanceMeters")
                        .HasColumnType("double precision");

                    b.Property<bool?>("LocationSuspicious")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ProvinceCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("WardCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WardName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA477A66ECEEE");

                    b.HasIndex(new[] { "Coordinates" }, "IX_Location_Coordinates");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "Coordinates" }, "IX_Location_Coordinates"), "gist");

                    b.HasIndex(new[] { "ProvinceName" }, "IX_Location_ProvinceName");

                    b.HasIndex(new[] { "ProvinceName", "DistrictName" }, "IX_Location_Province_District");

                    b.HasIndex(new[] { "ProvinceName", "DistrictName", "WardName" }, "IX_Location_Province_District_Ward");

                    b.ToTable("DiaDiem", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Medium", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("MediaID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MediaId"));

                    b.Property<bool?>("IsThumbnail")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("MediaURL");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("MediaId")
                        .HasName("PK__Media__B2C2B5AF03484D12");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_TepDaPhuongTien_Target");

                    b.ToTable("TepDaPhuongTien", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("MessageID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("integer")
                        .HasColumnName("ConversationID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("SenderAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("SenderAccountID");

                    b.HasKey("MessageId")
                        .HasName("PK_Messages");

                    b.HasIndex(new[] { "ConversationId", "CreatedAt" }, "IX_Messages_Conversation_Created");

                    b.HasIndex(new[] { "ConversationId", "MessageId" }, "IX_Messages_Conversation_Message");

                    b.HasIndex(new[] { "SenderAccountId", "CreatedAt" }, "IX_Messages_Sender_Created");

                    b.ToTable("TinNhan", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Notification", b =>
                {
                    b.Property<long>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NotificationID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text")
                        .HasColumnName("MetaJSON");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecipientAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("RecipientAccountID");

                    b.Property<int?>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("NotificationId")
                        .HasName("PK_Notifications");

                    b.HasIndex(new[] { "RecipientAccountId", "IsRead", "CreatedAt" }, "IX_Notifications_Recipient_Read_Time");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_Notifications_Target");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.PaymentOrder", b =>
                {
                    b.Property<int>("PaymentOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentOrderId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("VND");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("PayOS");

                    b.Property<string>("ProviderPaymentLinkId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RawWebhookJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PaymentOrderId");

                    b.HasIndex("AccountId");

                    b.HasIndex("OrderCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_PaymentOrders_OrderCode");

                    b.ToTable("PaymentOrders", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.PostAnalyticsDaily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationCount")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChatStartedCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer");

                    b.Property<int>("ListingImpressionCount")
                        .HasColumnType("integer");

                    b.Property<int>("MapImpressionCount")
                        .HasColumnType("integer");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UQ_PostAnalyticsDaily_Target_Date");

                    b.ToTable("PostAnalyticsDailies");
                });

            modelBuilder.Entity("UniMap360.Models.PostAnalyticsEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<int?>("ActorAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OwnerAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("SourcePage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("EventId");

                    b.HasIndex("ActorAccountId");

                    b.HasIndex("EventType", "OccurredAt")
                        .HasDatabaseName("IX_PostAnalyticsEvents_Type_OccurredAt");

                    b.HasIndex("OwnerAccountId", "OccurredAt")
                        .HasDatabaseName("IX_PostAnalyticsEvents_Owner_OccurredAt");

                    b.HasIndex("TargetType", "TargetId", "OccurredAt")
                        .HasDatabaseName("IX_PostAnalyticsEvents_Target_OccurredAt");

                    b.ToTable("PostAnalyticsEvents");
                });

            modelBuilder.Entity("UniMap360.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ReviewID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("TargetID");

                    b.Property<string>("TargetType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79AEF54E702E");

                    b.HasIndex(new[] { "TargetType", "TargetId" }, "IX_Review_Target");

                    b.HasIndex(new[] { "StudentId", "TargetType", "TargetId" }, "UX_Review_Student_Target")
                        .IsUnique();

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoomID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("CategoryID");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("HostId")
                        .HasColumnType("integer")
                        .HasColumnName("HostID");

                    b.Property<bool?>("IsExternal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("LocationID");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("RoomStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Available");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("SourceURL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RoomId")
                        .HasName("PK__Rooms__32863919894EE30F");

                    b.HasIndex("CategoryId");

                    b.HasIndex("HostId");

                    b.HasIndex("LocationId");

                    b.HasIndex(new[] { "SourceUrl" }, "UX_PhongTro_SourceURL")
                        .IsUnique();

                    b.ToTable("PhongTro", null, t =>
                        {
                            t.HasTrigger("trg_LogPriceChange");
                        });
                });

            modelBuilder.Entity("UniMap360.Models.RoomViewingAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("AppointmentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppointmentId"));

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HostId")
                        .HasColumnType("integer")
                        .HasColumnName("HostID");

                    b.Property<string>("HostResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("RoomID");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    b.Property<string>("StudentNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("SuggestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppointmentId")
                        .HasName("PK_RoomViewingAppointments");

                    b.HasIndex(new[] { "HostId", "Status", "ScheduledAt" }, "IX_RoomViewingAppointments_Host_Status_Scheduled");

                    b.HasIndex(new[] { "RoomId", "ScheduledAt" }, "IX_RoomViewingAppointments_Room_Scheduled");

                    b.HasIndex(new[] { "StudentId", "Status", "CreatedAt" }, "IX_RoomViewingAppointments_Student_Status_Created");

                    b.ToTable("LichXemPhong", null, t =>
                        {
                            t.HasTrigger("tr_LichXemPhong_LogTrangThai");
                        });
                });

            modelBuilder.Entity("UniMap360.Models.RoommatePost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaPreference")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("BudgetPerMonth")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Habits")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetGender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("RoommatePost", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("StudentID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    b.Property<string>("Cvlink")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("CVLink");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Major")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("University")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("StudentId")
                        .HasName("PK__StudentP__32C52A79F5EEC15A");

                    b.HasIndex(new[] { "AccountId" }, "UQ__StudentP__349DA5873B5BC4FE")
                        .IsUnique();

                    b.ToTable("HoSoSinhVien", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlanId"));

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PriceVnd")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RoleScope")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlanId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UQ_SubscriptionPlans_Code");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("UniMap360.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("LogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("AccountID");

                    b.Property<DateTime?>("ActionTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LogAction")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("LogId")
                        .HasName("PK__SystemLo__5E5499A8D6B10865");

                    b.HasIndex("AccountId");

                    b.ToTable("NhatKyHeThong", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.VGlobalMapFeed", b =>
                {
                    b.Property<string>("AddressText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<bool?>("IsExternal")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("character varying(4)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("SourceUrl");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("Value")
                        .HasColumnType("decimal(18, 2)");

                    b.ToTable((string)null);

                    b.ToView("v_GlobalMapFeed", (string)null);
                });

            modelBuilder.Entity("UniMap360.Models.AccountSubscription", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniMap360.Models.SubscriptionPlan", "Plan")
                        .WithMany("AccountSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("UniMap360.Models.ContentReport", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "ReporterAccount")
                        .WithMany()
                        .HasForeignKey("ReporterAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContentReports_ReporterAccount");

                    b.HasOne("UniMap360.Models.Account", "ReviewedByAdminAccount")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ContentReports_ReviewedByAdminAccount");

                    b.Navigation("ReporterAccount");

                    b.Navigation("ReviewedByAdminAccount");
                });

            modelBuilder.Entity("UniMap360.Models.ConversationParticipant", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationParticipants_Accounts");

                    b.HasOne("UniMap360.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConversationParticipants_Conversations");

                    b.Navigation("Account");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("EmployerProfile")
                        .HasForeignKey("UniMap360.Models.EmployerProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Emp_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Favorite", b =>
                {
                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("Favorites")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Fav_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.FeaturedListing", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("HostProfile")
                        .HasForeignKey("UniMap360.Models.HostProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Host_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.HasOne("UniMap360.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Cat");

                    b.HasOne("UniMap360.Models.EmployerProfile", "Employer")
                        .WithMany("Jobs")
                        .HasForeignKey("EmployerId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Emp");

                    b.HasOne("UniMap360.Models.Location", "Location")
                        .WithMany("Jobs")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Job_Loc");

                    b.Navigation("Category");

                    b.Navigation("Employer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniMap360.Models.JobApplication", b =>
                {
                    b.HasOne("UniMap360.Models.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .IsRequired()
                        .HasConstraintName("FK_App_Job");

                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("JobApplications")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_App_Student");

                    b.Navigation("Job");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.Message", b =>
                {
                    b.HasOne("UniMap360.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Conversations");

                    b.HasOne("UniMap360.Models.Account", "SenderAccount")
                        .WithMany("Messages")
                        .HasForeignKey("SenderAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Messages_Accounts");

                    b.Navigation("Conversation");

                    b.Navigation("SenderAccount");
                });

            modelBuilder.Entity("UniMap360.Models.Notification", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "RecipientAccount")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Accounts");

                    b.Navigation("RecipientAccount");
                });

            modelBuilder.Entity("UniMap360.Models.PaymentOrder", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.PostAnalyticsEvent", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "ActorAccount")
                        .WithMany()
                        .HasForeignKey("ActorAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("UniMap360.Models.Account", "OwnerAccount")
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorAccount");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("UniMap360.Models.Review", b =>
                {
                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Review_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.Room", b =>
                {
                    b.HasOne("UniMap360.Models.Category", "Category")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Cat");

                    b.HasOne("UniMap360.Models.HostProfile", "Host")
                        .WithMany("Rooms")
                        .HasForeignKey("HostId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Host");

                    b.HasOne("UniMap360.Models.Location", "Location")
                        .WithMany("Rooms")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_Room_Loc");

                    b.Navigation("Category");

                    b.Navigation("Host");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("UniMap360.Models.RoomViewingAppointment", b =>
                {
                    b.HasOne("UniMap360.Models.HostProfile", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Host");

                    b.HasOne("UniMap360.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Room");

                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_RoomViewingAppointments_Student");

                    b.Navigation("Host");

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.RoommatePost", b =>
                {
                    b.HasOne("UniMap360.Models.StudentProfile", "Student")
                        .WithMany("RoommatePosts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RoommatePosts_StudentProfile");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithOne("StudentProfile")
                        .HasForeignKey("UniMap360.Models.StudentProfile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Student_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.SystemLog", b =>
                {
                    b.HasOne("UniMap360.Models.Account", "Account")
                        .WithMany("SystemLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Log_Acc");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("UniMap360.Models.Account", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("EmployerProfile");

                    b.Navigation("HostProfile");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("StudentProfile");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("UniMap360.Models.Category", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.Conversation", b =>
                {
                    b.Navigation("ConversationParticipants");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("UniMap360.Models.EmployerProfile", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("UniMap360.Models.HostProfile", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.Job", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("UniMap360.Models.Location", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("UniMap360.Models.StudentProfile", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("JobApplications");

                    b.Navigation("Reviews");

                    b.Navigation("RoommatePosts");
                });

            modelBuilder.Entity("UniMap360.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("AccountSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
